before_script:
  - npm install

stages:
 - build
 - test

npmbuild:
  stage: build
  script:
    - npm run build
    - npm run lint:check

npmtest:
  stage: test
  script:
    - npm run test:unit
    - npm run test:cypress
