name: Build and run tests
on: [push,pull_request]
jobs:
  Build-And-Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
      - name: NPM Install
        run: npm install
      - name: NPM Build
        run: npm run build
      - name: NPM Linter
        run: npm run lint:check
      - name: NPM Test (Cypress)
        run: npm run test:cypress
